version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: projectpeterperplexity
    restart: always
    environment:
      POSTGRES_DB: projectpeter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
